name: sdt-lab5

services:
  student-db:
    image: postgres:16
    container_name: sdt-lab5-student-db
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    ports:
      - "5433:5432"
    networks:
      - sdt-lab5-net
    volumes:
      - sdt-lab5-student-db-data:/var/lib/postgresql/data

  student-service:
    build: ./student-service
    image: sdt-lab5-student-service
    container_name: sdt-lab5-student-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://student-db:5432/studentdb
      SPRING_DATASOURCE_USERNAME: student
      SPRING_DATASOURCE_PASSWORD: student
      SERVER_PORT: 8080
    ports:
      - "8081:8080"
    networks:
      - sdt-lab5-net

networks:
  sdt-lab5-net:
    driver: bridge

volumes:
  sdt-lab5-student-db-data:
